name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: ./templates/yootheme_dr/package-lock.json

      - name: Install and Compile CSS / JS
        run: |
          cd templates/yootheme_dr
          npm install
          npx mix -p

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo
          coverage: none
        env:
          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Composer dependencies
        run: |
          cd templates/yootheme_dr
          composer install

      - name: Zip Contents
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r release.zip ./ -x ./*.git* -x ./templates/yootheme_dr/node_modules/ -x ./templates/yootheme_dr/_dev/

      - name: Copy Zip over SSH
        uses: appleboy/scp-action@master
        with:
          source: "release.zip"
          target: "/home/u1853-meslzeqg4shb/www/daviderosina.com/public_html"
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSWORD }}
          port: 18765
          tar_tmp_path: "/home/u1853-meslzeqg4shb/www/daviderosina.com/public_html"

      - name: Unzip on server
        uses: appleboy/ssh-action@master
        with:
          username: ${{ secrets.SSH_USER }}
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSWORD }}
          port: 18765
          script: |
            cd /home/u1853-meslzeqg4shb/www/daviderosina.com/public_html
            unzip -o -d ./ release.zip
            rm release.zip

